/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:764af839-6eb9-4aab-b21c-46604d14b6b9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_tGi52HcxA",
    "aws_user_pools_web_client_id": "1dtfitnqnopggr1pe71fbj05ca",
    "oauth": {}
};


export default awsmobile;
